import "bootstrap/dist/css/bootstrap.css";
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700"
/>;
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapClient from "@/componets/providers/BootstrapProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}<BootstrapClient/></body>
    </html>
  );
}
